apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-example
  labels:
    app: maven-example
spec:
  progressDeadlineSeconds: 80
  replicas: 1
  selector:
    matchLabels:
      app: maven-example
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maven-example
    spec:
      restartPolicy: Always
      containers:
        - image: $IMAGE
          imagePullPolicy: Always
          name: example
          resources:
            requests:
              cpu: "20m"
              memory: "10M"
            limits:
              cpu: "100m"
              memory: "500M"
          livenessProbe:
            tcpSocket:
              port: 30004
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 30004
            initialDelaySeconds: 15
            timeoutSeconds: 3
          ports:
            - containerPort: 30004
---
kind: Service
apiVersion: v1
metadata:
  name: maven-example
  labels:
    name: maven-example
spec:
  selector:
    app: maven-example
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30004
